### ISSUE TITLE
iOS installation error

### ISSUE THREAD

**Issue by josexs** [Cap-go/native-market#1]
Hello!

I am trying to install the plugin in capacitor 3, but when compiling, it gives me a problem with iOS. attached error

`
✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!

[error] Analyzing dependencies
        [!] No podspec found for `CapgoNativeMarket` in
        `../../node_modules/@capgo/native-market``

Edit: When adding it from this repository in the node_modules folder, it works correctly

As always, thanks for your contributions!

**Comment by riderx** [comment]
Thanks for the report ! i changed the package name and forgot to add the new file to file list in package.json, new version will fix this
