### ISSUE TITLE
Issues using Bundle Identifier for NativeMarket.openStoreListing

### ISSUE THREAD

**Issue by glisom** [Cap-go/native-market#2]
Based on the usage documentation for `NativeMarket.openStoreListing`, it looks like bundle identifier should work on iOS. This causes an error when the App Store opens. From testing it seems like Apple Identifier from App Store Connect should be the id used for iOS. Would it be okay if I opened a PR to update the README? Or is this a bug that should not be happening?

Thanks!

**Comment by riderx** [comment]
Hello @glisom sorry for the delay i didn't get email for your issue.
yes that how it should work and how it work on my side.
what is the error you get ?
i'm not sure to understand "bundle identifier" is different for you to "Apple Identifier" ?

**Comment by riderx** [comment]
hey yes you are not the first one ! i just found the issue, i did publish a new version who should fix it! `1.10.0` can you try it ?

**Comment by riderx** [comment]
fixed on [v1.0.12](https://github.com/Cap-go/native-market/releases/tag/v1.0.12)
