### ISSUE TITLE
Fatal error: Index out of range

### ISSUE THREAD

**Issue by imanz7** [Cap-go/native-market#22]
Using openStoreListing and tried to put appid for ios by following the requirement (e.g. 'id1234567890'), however the error popup saying the index is out of range at urlStore line. This applies to other public apps that I have tried.

**Comment by tobiloeb** [comment]
I got the same error currently :(
![image](https://user-images.githubusercontent.com/8022875/230365413-3cee52f9-473b-4541-85ca-0db391d8af8e.png)

**Comment by riderx** [comment]
Hey @imanz7 sorry for the delay of anwser, i don't understand why you saw 'id1234567890', to open you should give this id who look like `com.myapp.app`
