### ISSUE TITLE
Change url to iTunes (https instead of http)

### ISSUE THREAD

**Issue by gosantoro** [Cap-go/native-market#24]
Our app has a security layer, provided by Appdome, that invalidates requests to non-secure url and that´s because of MiTM prevention (for further info, check this: https://www.appdome.com/how-to/mobile-app-security/man-in-the-middle-attack-prevention/use-ios-tls-ssl-certificate-validation-prevent-mitm-attacks/)

So when the app tries to open iTunes, the app fails because in the file "/@capgo/native-market/ios/Plugin/Plugin.swift (line 36)" , it is hardcoded the following url: **_http://itunes.apple.com_**.

Please would it be possible to change to https in future release? Currently, iTunes redirects http to https.

Thanks in advance.

**Comment by riderx** [comment]
should be fixed
