### ISSUE TITLE
Capacitor V5 Android incompatibility 

### ISSUE THREAD

**Issue by klaurtar** [Cap-go/native-market#27]
This package is causing errors when upgrading to capacitor V5. https://capacitorjs.com/docs/updating/plugins/5-0

**Comment by Galileon-venta** [comment]
Yes indeed it is; For me it worked to still enable Jetifier in the gradle.properties:
`android.enableJetifier=true`
but this is just a workaround; this library needs to be updated

**Comment by riderx** [comment]
Been fixed in latest :)
